jwt:
  secret: localocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocal
  expiration:
    access-token: 1814400000
    refresh-token: 2592000000
  access-header: Authorization
  refresh-header: Refresh
  grant-type: Bearer
  user-key: USER

oauth:
  kakao:
    public-key-info: https://kauth.kakao.com/.well-known/jwks.json

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
    username: postgres.yetashissrtrcdukgnqy
    password: timote123!!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false

  sql:
    init:
      mode: never

server:
  port: 8081
